SELECT * FROM FUN_FUNCIONARIOS; --selecionar toda tabela fun_funcionarios

SELECT FUN_NOME FROM FUN_FUNCIONARIOS;--selecionar coluna fun_nome da tabela fun_funcionarios

SELECT FUN_NOME+' '+FUN_SOBRENOME --concactenar fun_nome + fun_sobrenome
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;-- dou o apelido (AS) de nome_completo pra coluna

SELECT FUN_NOME+' '+FUN_SOBRENOME + ', '+ CAST(ISNULL(FUN_OBSERVACOES, '') AS VARCHAR)--cast(isnull) eu passo o tipo do valor fun_observacoes para um varchar
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;--dou o apelido de nome_completo e pra sgunda coluna de fun_data_nascimento

SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) --concacteno fun_nome e fun_sobrenome
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;--dou o apelido de nome_completo e fun_data_nascimento

SELECT SQL_VARIANT_PROPERTY ( FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(ISNULL(FUN_OBSERVACOES, '') AS VARCHAR), 'BaseType') --retorna o tipo das minhas variaveis
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;
SELECT TOP 1 SQL_VARIANT_PROPERTY ( FUN_NOME + ' ' + FUN_SOBRENOME + ', ' + CAST(ISNULL(FUN_OBSERVACOES, '') AS VARCHAR), 'BaseType') --retorna o tipo das minhas variaveis
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

SELECT SQL_VARIANT_PROPERTY(CONCAT(FUN_NOME,' ',FUN_SOBRENOME), 'BaseType') --retorna o tipo das minhas variaveis
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

SELECT TOP 1 SQL_VARIANT_PROPERTY(CONCAT(FUN_NOME,' ',FUN_SOBRENOME), 'BaseType') --retorna o tipo das minhas variaveis
AS NOME_COMPLETO, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS;

SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_DATA_NASCIMENTO --concactena a coluna fun-Nome e Fun_sobrenome 
FROM FUN_FUNCIONARIOS WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980; 

SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_DATA_NASCIMENTO
FROM FUN_FUNCIONARIOS WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980 AND MONTH(FUN_DATA_NASCIMENTO) = 02; --traz meu funcionrios com as codicoes de year e month

SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_DATA_NASCIMENTO 
FROM FUN_FUNCIONARIOS WHERE YEAR(FUN_DATA_NASCIMENTO) = 1980 AND MONTH(FUN_DATA_NASCIMENTO) = 02 OR MONTH(FUN_DATA_NASCIMENTO) = 08;--traz meu funcionario com algumas condicoes

SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_DATA_NASCIMENTO 
FROM FUN_FUNCIONARIOS WHERE DATEDIFF(YEAR, FUN_DATA_NASCIMENTO, GETDATE()) >= 25;--traz meu funcionario com as condicoes diferenca de ano (year) >= 25

SELECT FUN_NOME, FUN_SOBRENOME FROM FUN_FUNCIONARIOS WHERE FUN_OBSERVACOES IS NULL;--traz meu funcoinario (nome e sobrenome) que tem a observacao como nulo

SELECT FUN_NOME, FUN_SOBRENOME FROM FUN_FUNCIONARIOS WHERE FUN_OBSERVACOES IS NOT NULL;

SELECT * FROM FUN_FUNCIONARIOS WHERE FUN_NOME = 'JOÃO'
COLLATE LATIN1_GENERAL_CI_AI;--configuracao da minha instancia
