SELECT * FROM FUN_FUNCIONARIOS;

CREATE TABLE PAC_PONTOS_ACESSO--crio uma tabela pac_pontos_acesso
(
	PAC_ID INT IDENTITY(1,1) PRIMARY KEY,--minha coluna que sera minha chave primaria
	PAC_DATA_INICIAL DATETIME NOT NULL,--minha coluna do tipo datetime nao nulo
	PAC_DATA_FINAL DATETIME DEFAULT NULL,--minha coluna do tipo datetime que se nao tiver valor retornara um nulo
	FUN_ID INT NOT NULL--id do tipo int nao nulo
);

ALTER TABLE PAC_PONTOS_ACESSO --alterar tabela
ADD CONSTRAINT FK_PAC_PONTOS_ACESSO__FUN_FUNCIONARIOS__FUN_ID--adiciono uma restrição  
FOREIGN KEY(FUN_ID) REFERENCES FUN_FUNCIONARIOS(FUN_ID); --minha chave estrangeira fun_id que faz uma referencia a tabela fun_funcionarios

INSERT INTO PAC_PONTOS_ACESSO (PAC_DATA_INICIAL, FUN_ID)--inserto pac_inial e fun_id
VALUES ('2017-02-01 07:00:00', 2)--valores de pac_data_incial e fun_id

SELECT * FROM PAC_PONTOS_ACESSO;--seleciono toda minha tabela pac_pontos_acesso

ALTER TABLE PAC_PONTOS_ACESSO ADD CONSTRAINT CK_PAC_PONTOS_ACESSO__DATA_INICIAL_DATA_FINAL--altero minha tabela e adiciono uma restrição 
CHECK -- "chekando"
(
	PAC_DATA_INICIAL < PAC_DATA_FINAL AND 
	DAY(PAC_DATA_INICIAL) = DAY(PAC_DATA_FINAL) AND
	MONTH(PAC_DATA_INICIAL) = MONTH(PAC_DATA_FINAL) AND
	YEAR(PAC_DATA_INICIAL) = YEAR(PAC_DATA_FINAL)
);

UPDATE PAC_PONTOS_ACESSO SET PAC_DATA_FINAL = '2017-02-01 12:00:00'--atualizo e 'seto' minha coluna pac_data_final
WHERE PAC_ID = 3;--meu filtro

SELECT *, CAST(PAC_DATA_FINAL - PAC_DATA_INICIAL AS TIME(0)) AS DIFERENCA_DATAS
FROM PAC_PONTOS_ACESSO;

SELECT *, CONVERT(TIME(0), PAC_DATA_FINAL - PAC_DATA_INICIAL) AS DIFERENCA_DATAS
FROM PAC_PONTOS_ACESSO;

SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC.PAC_DATA_INICIAL,
PAC.PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN
INNER JOIN PAC_PONTOS_ACESSO AS PAC
ON FUN.FUN_ID = PAC.FUN_ID;

INSERT INTO PAC_PONTOS_ACESSO (PAC_DATA_INICIAL, PAC_DATA_FINAL, FUN_ID)
VALUES ('2017-02-01 07:03:00', '2017-02-01 11:57:00', 4);

SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC.PAC_DATA_INICIAL,
PAC.PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN
RIGHT JOIN PAC_PONTOS_ACESSO AS PAC
ON FUN.FUN_ID = PAC.FUN_ID;

SELECT CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC.PAC_DATA_INICIAL,
PAC.PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN
LEFT JOIN PAC_PONTOS_ACESSO AS PAC
ON FUN.FUN_ID = PAC.FUN_ID;