CREATE TABLE DEP_DEPARTAMENTOS
(
	DEP_ID INT IDENTITY(1,1) PRIMARY KEY,
	DEP_NOME VARCHAR(50) NOT NULL
);

INSERT INTO DEP_DEPARTAMENTOS (DEP_NOME)--insertando duas colunas
VALUES ('RECURSOS HUMANOS'), ('TECNOLOGIA DA INFORMAÇÃO'), ('CONTROLADORIA');--adicioanndo valores a minha tupla (linha)

SELECT * FROM DEP_DEPARTAMENTOS;

ALTER TABLE FUN_FUNCIONARIOS ADD DEP_ID INT NOT NULL DEFAULT 1;

SELECT * FROM FUN_FUNCIONARIOS;

ALTER TABLE FUN_FUNCIONARIOS ADD CONSTRAINT FK_FUN_FUNCIONARIOS__DEP_DEPARTAMENTOS__DEP_ID
FOREIGN KEY(DEP_ID) REFERENCES DEP_DEPARTAMENTOS(DEP_ID);

UPDATE FUN_FUNCIONARIOS SET DEP_ID = 2 WHERE FUN_ID = 2; --tualizando  dep_id do meu usuario de id =2
UPDATE FUN_FUNCIONARIOS SET DEP_ID = 3 WHERE FUN_ID IN (3, 4);  --atualizando o dep_id do meu usuario de id = 3 e 4

ALTER TABLE DEP_DEPARTAMENTOS ADD FUN_ID_RESPONSAVEL INT NOT NULL DEFAULT 1;--alterando a tabela dep_departamentos e adicionanado a coluna fun_id_responsavel do tipo int nao nulo e se nao tiver valor, coloco o 1

SELECT * FROM DEP_DEPARTAMENTOS;

ALTER TABLE DEP_DEPARTAMENTOS ADD CONSTRAINT FK_DEP_DEPARTAMENTOS__FUN_FUNCIONARIOS__FUN_ID_RESPONSAVEL
FOREIGN KEY(FUN_ID_RESPONSAVEL) REFERENCES FUN_FUNCIONARIOS(FUN_ID);--chave estrangeira que faz uma referencia a tabela fun_funcionarios

UPDATE DEP_DEPARTAMENTOS SET FUN_ID_RESPONSAVEL = 2 WHERE DEP_ID = 2;

UPDATE DEP_DEPARTAMENTOS SET FUN_ID_RESPONSAVEL = 4 WHERE DEP_ID = 3;

SELECT DEP.DEP_NOME AS DEPARTAMENTO,
CONCAT(FUN2.FUN_SOBRENOME, ', ', FUN2.FUN_NOME) AS RESPONSAVEL_DEPARTAMENTO,
CONCAT(FUN.FUN_SOBRENOME, ', ', FUN.FUN_NOME) AS FUNCIONARIO,
PAC.PAC_DATA_INICIAL,
PAC.PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS--convertendo minhas variaveis para o tipo time depois faço a substração criando uma nova coluna que dei o apelido de horas_trabalhadas
FROM FUN_FUNCIONARIOS FUN
LEFT JOIN PAC_PONTOS_ACESSO AS PAC --pegando os dados da coluna que esta em frente o from
ON FUN.FUN_ID = PAC.FUN_ID
INNER JOIN DEP_DEPARTAMENTOS AS DEP--pegando os dados em comum
ON FUN.DEP_ID = DEP.DEP_ID
INNER JOIN FUN_FUNCIONARIOS AS FUN2 --pegando so dadso em comum
ON DEP.FUN_ID_RESPONSAVEL = FUN2.FUN_ID
